# Login using email and password using firebase auth
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "test.email@email.com",
  "password": "password123"
}

###

# Verify a token and get uid from the token
POST http://localhost:3000/auth/verifyToken
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjFlNTIxYmY1ZjdhNDAwOGMzYmQ3MjFmMzk2OTcwOWI1MzY0MzA5NjEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vdGVzdGNsYXNzY2FwdHVyZSIsImF1ZCI6InRlc3RjbGFzc2NhcHR1cmUiLCJhdXRoX3RpbWUiOjE3MzE2ODY2MzEsInVzZXJfaWQiOiJBSDdGWjI3ZTRJVkNwaDBhMmpJZmZFQ3R6U0gyIiwic3ViIjoiQUg3RloyN2U0SVZDcGgwYTJqSWZmRUN0elNIMiIsImlhdCI6MTczMTY4NjYzMSwiZXhwIjoxNzMxNjkwMjMxLCJlbWFpbCI6InRlc3QuZW1haWxAZW1haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbInRlc3QuZW1haWxAZW1haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.QVm2fwc7-kYPM_cx5lWejX4tGLYV92AZz05xGnBiGAexAOyLm7n37SjLTpgxe1u4fxuQOMa2RYwtmFPO0frNYKWv_GccD7ZGY2jIXg_kZpw_wOvu3CME3KJTf9lgDa3CZ5lobq1W_HbhwHysuR2Hfi11pQMiVuwfNRHR6j9ByNbibHPmB9PJEFx8xPfNTBtSF4ZRwaB_rPrlq_aJxvvmDsatVXl46zBArOPSKzkku3_IxftCFP28wVfLuaB16FzOw3TfT05efTBrqHJT17a15iWr59lmabDd_LB6v2bPGmSQkK7yMOvxaqg26WnxyPcdsPEOCr_5FKFjTGdEORo1XQ

{
  "idToken": "eyJhbGciOiJSUzI1NiIsImtpZCI6IjFlNTIxYmY1ZjdhNDAwOGMzYmQ3MjFmMzk2OTcwOWI1MzY0MzA5NjEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vdGVzdGNsYXNzY2FwdHVyZSIsImF1ZCI6InRlc3RjbGFzc2NhcHR1cmUiLCJhdXRoX3RpbWUiOjE3MzE2ODY2MzEsInVzZXJfaWQiOiJBSDdGWjI3ZTRJVkNwaDBhMmpJZmZFQ3R6U0gyIiwic3ViIjoiQUg3RloyN2U0SVZDcGgwYTJqSWZmRUN0elNIMiIsImlhdCI6MTczMTY4NjYzMSwiZXhwIjoxNzMxNjkwMjMxLCJlbWFpbCI6InRlc3QuZW1haWxAZW1haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbInRlc3QuZW1haWxAZW1haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.QVm2fwc7-kYPM_cx5lWejX4tGLYV92AZz05xGnBiGAexAOyLm7n37SjLTpgxe1u4fxuQOMa2RYwtmFPO0frNYKWv_GccD7ZGY2jIXg_kZpw_wOvu3CME3KJTf9lgDa3CZ5lobq1W_HbhwHysuR2Hfi11pQMiVuwfNRHR6j9ByNbibHPmB9PJEFx8xPfNTBtSF4ZRwaB_rPrlq_aJxvvmDsatVXl46zBArOPSKzkku3_IxftCFP28wVfLuaB16FzOw3TfT05efTBrqHJT17a15iWr59lmabDd_LB6v2bPGmSQkK7yMOvxaqg26WnxyPcdsPEOCr_5FKFjTGdEORo1XQ"
}

###

# Sign up a user using email and password
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "test.email@email.com",
    "password": "password123"
}

<> 2024-11-14T102701.201.json

###